# Generated by Django 2.2.2 on 2020-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='days',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='opening_hours',
            field=models.DateTimeField(null=True),
        ),
    ]
