# Generated by Django 2.2.2 on 2020-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyway', '0002_auto_20200728_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
