# Generated by Django 2.2.2 on 2020-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyway', '0003_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent_car',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
